### ISSUE TITLE
missing hex file

### ISSUE THREAD

**Issue by altarace** [3d-printing-canada/CR10V2-BLtouch-Installation#1]
Instructions say there is a hex file in the repo and source in folder. Cannot find it. Can you please add?

**Comment by nicholashooper** [comment]
I also cannot find this

**Comment by andycrane** [comment]
Great video and how-to docs but no hex file. Would love the hex file please.

**Comment by nicholashooper** [comment]
I found a working HEX file directly from the manufacturer.
Creality provides these files on their site.
https://www.creality3dofficial.com/pages/firmware-download
I was having trouble getting it to work with random youtube videos, creality has documentation for everything, just gotta do a little digging.

**Comment by mpisat** [comment]
Where is the TH3D firmware hex file??

**Comment by never2befinished** [comment]
When you click the github link from 3dprintingcanada's youtube video, it opens on the README. Click the green download button at the top right and save the .zip. Or just download this. Open it with XLoader and you're done. Easy peesy. 
[CR10V2-BLtouch-Installation-master.zip](https://github.com/3d-printing-canada/CR10V2-BLtouch-Installation/files/4017552/CR10V2-BLtouch-Installation-master.zip)

**Comment by altarace** [comment]
fixed, hex file is in repo. Thank you!
